SELECT MIN(EMP.SAL) 
FROM EMP;

SELECT MIN(EMP.SAL) AS MENOR, MAX(EMP.SAL) AS MAIOR, ROUND( AVG(EMP.SAL), 2) AS MEDIA  
FROM EMP;

SELECT EMP.JOB, MAX(EMP.SAL) AS MAIOR, MIN(EMP.SAL) AS MENOR
FROM EMP
GROUP BY EMP.JOB;

SELECT JOB, COUNT(JOB)
FROM EMP
WHERE JOB = 'MANAGER'
GROUP BY JOB;

SELECT JOB, AVG(SAL) AS SALMEDIO, AVG((SAL + COALESCE(COMM, 0)) * 14) AS MEDIAANUAL
FROM EMP
GROUP BY JOB
ORDER BY SALMEDIO DESC;

SELECT MAX(SAL) - MIN(SAL) AS DIFERENÇA
FROM EMP;

SELECT DEPT.DNAME, COUNT(DEPT.DNAME)
FROM DEPT
INNER JOIN EMP ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DNAME 
HAVING COUNT(EMP.EMPNO) > 3;

SELECT CHEF.ENAME, MIN(EMP.SAL) AS MENOR 
FROM EMP
INNER JOIN EMP CHEF ON EMP.MGR = CHEF.EMPNO
GROUP BY CHEF.ENAME 
HAVING MIN(EMP.SAL) > 1000
ORDER BY MIN(EMP.SAL) ASC;
                                                             