CREATE TABLE PAIS (
CD_PAIS INTEGER,
DS_PAIS VARCHAR(50),
CONSTRAINT PK_PAIS PRIMARY KEY (CD_PAIS));

CREATE TABLE ESTADO (
CD_ESTADO INTEGER,
CD_PAIS INTEGER,
DS_ESTADO VARCHAR(50),
CONSTRAINT FK_PAIS FOREIGN KEY (CD_PAIS) REFERENCES PAIS (CD_PAIS),
CONSTRAINT PK_ESTADO PRIMARY KEY (CD_ESTADO));

CREATE TABLE CIDADE (
CD_CIDADE INTEGER,
CD_ESTADO INTEGER,
DS_CIDADE VARCHAR(50),
NR_CEP INTEGER,
CONSTRAINT PK_CIDADE PRIMARY KEY (CD_CIDADE),
CONSTRAINT FK_ESTADO FOREIGN KEY (CD_ESTADO) REFERENCES ESTADO (CD_ESTADO));

CREATE TABLE CLIENTE (
CD_CLIENTE INTEGER,
CD_CIDADE INTEGER,
NM_CLIENTE VARCHAR(100) NOT NULL,
NR_ENDERECO INTEGER NOT NULL,
NM_RUA VARCHAR(100) NOT NULL,
DS_COMPLEMENTO VARCHAR(100) NOT NULL,
NM_BAIRRO VARCHAR(100) NOT NULL,
NR_FONERES NUMERIC(11) NOT NULL,
NR_FONECELU NUMERIC(11) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CD_CLIENTE),
CONSTRAINT FK_CIDADE FOREIGN KEY (CD_CIDADE) REFERENCES CIDADE (CD_CIDADE));

CREATE TABLE CLIENTE_FISICO (
CD_CLIENTE INTEGER,
NR_CPF NUMERIC(11) NOT NULL,
NR_RG NUMERIC(20) NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY (CD_CLIENTE) REFERENCES CLIENTE (CD_CLIENTE),
CONSTRAINT PK_CLIENTE_FISICO PRIMARY KEY (CD_CLIENTE));

CREATE TABLE CLIENTE_JURIDICO (
CD_CLIENTE INTEGER,
NR_CNPJ NUMERIC(14) NOT NULL,
NR_INSCRICAO NUMERIC(16) NOT NULL,
CONSTRAINT FK_CLIENTE_ FOREIGN KEY (CD_CLIENTE) REFERENCES CLIENTE (CD_CLIENTE),
CONSTRAINT PK_CLIENTE_JURIDICO PRIMARY KEY (CD_CLIENTE));

CREATE TABLE OPERADORA (
CD_OPERADORA INTEGER,
NM_OPERADORA VARCHAR(30) NOT NULL,
CONSTRAINT PK_OPERADORA PRIMARY KEY (CD_OPERADORA)
);

CREATE TABLE BANDEIRA (
CD_BANDEIRA INTEGER,
CD_OPERADORA INTEGER,
NM_BANDEIRA VARCHAR(30) NOT NULL,
CONSTRAINT FK_OPERADORA FOREIGN KEY (CD_OPERADORA) REFERENCES OPERADORA (CD_OPERADORA),
CONSTRAINT PK_BANDEIRA PRIMARY KEY (CD_BANDEIRA)
);

CREATE TABLE TIPO (
CD_TIPO INTEGER,
DS_TIPO VARCHAR(30) NOT NULL,
CONSTRAINT PK_TIPO PRIMARY KEY (CD_TIPO)
);

CREATE TABLE CONTA (
CD_CONTA INTEGER,
CD_TIPO INTEGER,
CONSTRAINT FK_TIPO FOREIGN KEY (CD_TIPO) REFERENCES TIPO (CD_TIPO),
CONSTRAINT PK_CONTA PRIMARY KEY (CD_CONTA)
);

CREATE TABLE BANCO (
CD_BANCO INTEGER,
NM_BANCO VARCHAR (50) NOT NULL,
CONSTRAINT PK_BANCO PRIMARY KEY (CD_BANCO)
);

CREATE TABLE AGENCIA (
CD_AGENCIA INTEGER,
CD_BANCO INTEGER,
CD_CIDADE INTEGER,
NM_RUA VARCHAR(100) NOT NULL,
NR_RUA INTEGER NOT NULL,
NR_TELEFONE INTEGER NOT NULL,
DS_COMPLEMENTO VARCHAR(50) NOT NULL,
NM_BAIRRO VARCHAR(50) NOT NULL,
CONSTRAINT FK_BANCO FOREIGN KEY (CD_BANCO) REFERENCES BANCO (CD_BANCO),
CONSTRAINT FK_CIDADE_ FOREIGN KEY (CD_CIDADE) REFERENCES CIDADE (CD_CIDADE),
CONSTRAINT PK_AGENCIA PRIMARY KEY (CD_AGENCIA, CD_BANCO)
);

CREATE TABLE CONTA_CLIENTE (
CD_CLIENTE INTEGER,
CD_CONTA INTEGER,
CD_BANCO INTEGER,
CD_AGENCIA INTEGER,
VL_LIMITE NUMBER(8,2),r
VL_SALDO NUMBER(8,2),
CONSTRAINT FK_AGENCIA_ FOREIGN KEY (CD_AGENCIA, CD_BANCO) REFERENCES AGENCIA (CD_AGENCIA, CD_BANCO),
CONSTRAINT FK_CLIENTE_C FOREIGN KEY (CD_CLIENTE) REFERENCES CLIENTE (CD_CLIENTE),
CONSTRAINT FK_CONTA FOREIGN KEY (CD_CONTA) REFERENCES CONTA (CD_CONTA),
CONSTRAINT PK_CONTA_CLIENTE PRIMARY KEY (CD_CLIENTE, CD_CONTA));

CREATE TABLE OPERACAO (
CD_OPERACAO INTEGER,
CD_CONTA INTEGER,
CD_BANCO INTEGER,
CD_CLIENTE INTEGER,
CD_AGENCIA INTEGER,
DT_OPERACAO DATE NOT NULL,
HR_OPERACAO DATE NOT NULL,
CONSTRAINT FK_AGENCIA FOREIGN KEY (CD_AGENCIA, CD_BANCO) REFERENCES AGENCIA(CD_AGENCIA, CD_BANCO),
CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (CD_CLIENTE, CD_CONTA) REFERENCES CONTA_CLIENTE (CD_CLIENTE, CD_CONTA),
CONSTRAINT PK_OPERACAO PRIMARY KEY (CD_OPERACAO));

CREATE TABLE CARTAO (
CD_CARTAO INTEGER,
CD_CONTA INTEGER,
CD_BANDEIRA INTEGER,
CD_CLIENTE INTEGER,
CONSTRAINT FK_BANDEIRA FOREIGN KEY (CD_BANDEIRA) REFERENCES BANDEIRA (CD_BANDEIRA),
CONSTRAINT FK_CONTA_CLIENTE_CART FOREIGN KEY (CD_CONTA, CD_CLIENTE) REFERENCES CONTA_CLIENTE (CD_CONTA, CD_CLIENTE),
CONSTRAINT PK_CARTAO PRIMARY KEY (CD_CARTAO)
);

CREATE TABLE PAGAMENTO (
CD_OPERACAO INTEGER,
CD_CONTA_BENEFICIADO INTEGER,
CD_CLIENTE_BENEFICIADO INTEGER, 
VL_PAGAMENTO NUMBER(7,2) NOT NULL,
CONSTRAINT FK_CONTA_CLI_BENEFICADO FOREIGN KEY (CD_CONTA_BENEFICIADO, CD_CLIENTE_BENEFICIADO) REFERENCES CONTA_CLIENTE (CD_CLIENTE, CD_CONTA),
CONSTRAINT FK_OPERACAO1 FOREIGN KEY (CD_OPERACAO) REFERENCES OPERACAO (CD_OPERACAO),
CONSTRAINT PK_PAGAMENTO PRIMARY KEY (CD_OPERACAO)
);

CREATE TABLE TRANSFERENCIA (
CD_OPERACAO INTEGER,
CD_CONTA_DESTINATARIO INTEGER,
CD_CLIENTE_DESTINATARIO INTEGER,
VL_TRANSFERENCIA NUMBER(7,2),
CONSTRAINT FK_CONTA_CLI_BENEFICADO_ FOREIGN KEY (CD_CONTA_DESTINATARIO, CD_CLIENTE_DESTINATARIO) REFERENCES CONTA_CLIENTE (CD_CLIENTE, CD_CONTA),
CONSTRAINT FK_OPERACAO2 FOREIGN KEY (CD_OPERACAO) REFERENCES OPERACAO (CD_OPERACAO),
CONSTRAINT PK_TRANSFERENCIA PRIMARY KEY (CD_OPERACAO)
);

CREATE TABLE SALDO (
CD_OPERACAO INTEGER,
VL_SALDO NUMERIC(7,2) NOT NULL,
CONSTRAINT FK_OPERACAO3 FOREIGN KEY (CD_OPERACAO) REFERENCES OPERACAO (CD_OPERACAO),
CONSTRAINT PK_SALDO PRIMARY KEY (CD_OPERACAO)
);

CREATE TABLE DEPOSITO (
CD_OPERACAO INTEGER,
VL_DEPOSITO NUMBER(7,2) NOT NULL,
CD_CONTA_BENEFICIADO INTEGER,
CD_CLIENTE_BENEFICIADO INTEGER, 
VL_PAGAMENTO NUMBER(7,2) NOT NULL,
CONSTRAINT FK_CONTA_CLI_BENEFICADO__ FOREIGN KEY (CD_CONTA_BENEFICIADO, CD_CLIENTE_BENEFICIADO) REFERENCES CONTA_CLIENTE (CD_CLIENTE, CD_CONTA),
CONSTRAINT FK_OPERACAO4 FOREIGN KEY (CD_OPERACAO) REFERENCES OPERACAO (CD_OPERACAO),
CONSTRAINT PK_DEPOSITO PRIMARY KEY (CD_OPERACAO)
);

CREATE TABLE SAQUE (
CD_OPERACAO INTEGER,
VL_SAQUE NUMERIC(7,2) NOT NULL,
CONSTRAINT FK_OPERACAO5 FOREIGN KEY (CD_OPERACAO) REFERENCES OPERACAO (CD_OPERACAO),
CONSTRAINT PK_SAQUE PRIMARY KEY (CD_OPERACAO)
);