/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.prova.grupointegrado.view;

import br.prova.grupointegrado.controlhe.ClassAbastecedor;
import br.prova.grupointegrado.controlhe.ClassAbastecimento;
import br.prova.grupointegrado.controlhe.ClassVeiculo;
import br.prova.grupointegrado.ferramenta.PreencherJTable;

/**
 *
 * @author CrasyFox
 */
public class JFrameAbastecimento extends javax.swing.JFrame {
    ClassAbastecimento abastecimento = new ClassAbastecimento();
    ClassAbastecedor abastecedor = new ClassAbastecedor();
    ClassVeiculo veiculo = new ClassVeiculo();
    PreencherJTable preencher = new PreencherJTable();
    int chaveAbastecedor[];
    int chaveVeiculo[];
    /**
     * Creates new form JFrameAbastecimento
     */
    public JFrameAbastecimento() {
        initComponents();
        jTFCdAbastecimento.setText(abastecimento.autoIncrem("MOV_ABASTECIMENTO","CD_ABASTECIMENTO"));
        chaveAbastecedor = preencher.preencherComboRetorno(abastecedor.consultaAbastecedor(), "NM_ABASTECEDOR", "CD_ABASTECEDOR", jCBAbastecedor);
        chaveVeiculo = preencher.preencherComboRetorno(veiculo.consultaVeiculo(), "DS_VEICULO", "CD_VEICULO", jCBVeiculo);
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCdAbastecimento = new javax.swing.JTextField();
        jCBVeiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBAbastecedor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTFQTAbastecido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFKM = new javax.swing.JTextField();
        Data = new javax.swing.JLabel();
        jTFData = new javax.swing.JTextField();
        jTBIncluir = new javax.swing.JToggleButton();
        jTBExcluir = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jCBConsulta = new javax.swing.JComboBox<>();
        jTFConsulta = new javax.swing.JTextField();
        jTBPesquisa = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTconsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cod:");

        jLabel2.setText("Veiculo");

        jLabel3.setText("Abastecedor");

        jLabel4.setText("Quantidade");

        jLabel5.setText("KM");

        Data.setText("Data");

        jTBIncluir.setText("Incluir");
        jTBIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBIncluirActionPerformed(evt);
            }
        });

        jTBExcluir.setText("Excluir");
        jTBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jTFCdAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jCBAbastecedor, 0, 346, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTBIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTFQTAbastecido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFKM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Data)
                                    .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addComponent(jTBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCdAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jCBAbastecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(Data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFQTAbastecido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBIncluir)
                    .addComponent(jTBExcluir))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Abastecimento", jPanel1);

        jCBConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Abastecedor", "Veiculo" }));

        jTBPesquisa.setText("Pesquisar");
        jTBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBPesquisaActionPerformed(evt);
            }
        });

        jTconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cod.Veiculo", "Nome Abastecedor", "KM", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTconsulta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(jTBPesquisa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBPesquisa))
                    .addComponent(jCBConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTBIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBIncluirActionPerformed
        
        abastecimento.setCdVeiculo(chaveVeiculo[jCBVeiculo.getSelectedIndex()]);
        abastecimento.setCdAbastecedor(chaveAbastecedor[jCBAbastecedor.getSelectedIndex()]);
        abastecimento.setVlKM(Integer.parseInt(jTFKM.getText()));
        abastecimento.setQtAbastecido(Integer.parseInt(jTFQTAbastecido.getText()));
        abastecimento.setDtAbastecimento(jTFData.getText());
        abastecimento.incluirAbastecimento();
        limpar();
        jTFCdAbastecimento.setText(abastecimento.autoIncrem("MOV_ABASTECIMENTO","CD_ABASTECIMENTO"));
        
    }//GEN-LAST:event_jTBIncluirActionPerformed

    private void jTBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBExcluirActionPerformed
        abastecimento.setCdAbastecimento(Integer.parseInt(jTFCdAbastecimento.getText()));
        abastecimento.excluirAbastecimento();
        limpar();
        jTFCdAbastecimento.setText(abastecimento.autoIncrem("MOV_ABASTECIMENTO","CD_ABASTECIMENTO"));
    }//GEN-LAST:event_jTBExcluirActionPerformed

    private void jTBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBPesquisaActionPerformed
        switch(jCBConsulta.getSelectedIndex()){
            case 0:
                preencher.preencherJtable(jTconsulta, abastecimento.consultaGeral());
               break;
               
               case 1:
                   abastecimento.setNmAbastecedor(jTFConsulta.getText());
                   preencher.preencherJtable(jTconsulta, abastecimento.consultaAbastecedor());
               break;
               
               case 2:
                   abastecimento.setNmVeiculo(jTFConsulta.getText());
                   preencher.preencherJtable(jTconsulta, abastecimento.consultaVeiculo());
               break;                
        }
    }//GEN-LAST:event_jTBPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAbastecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAbastecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAbastecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAbastecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAbastecimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Data;
    private javax.swing.JComboBox<String> jCBAbastecedor;
    private javax.swing.JComboBox<String> jCBConsulta;
    private javax.swing.JComboBox<String> jCBVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jTBExcluir;
    private javax.swing.JToggleButton jTBIncluir;
    private javax.swing.JToggleButton jTBPesquisa;
    private javax.swing.JTextField jTFCdAbastecimento;
    private javax.swing.JTextField jTFConsulta;
    private javax.swing.JTextField jTFData;
    private javax.swing.JTextField jTFKM;
    private javax.swing.JTextField jTFQTAbastecido;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTconsulta;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        jTFQTAbastecido.setText("");
        jTFKM.setText("");
        jTFData.setText("");
    }
}
