CREATE TABLE CLIENTE (
CD_CLIENTE INTEGER NOT NULL,
NM_CLIENTE VARCHAR(100) NOT NULL,
NR_ENDERECO INTEGER NOT NULL,
NM_RUA VARCHAR(100) NOT NULL,
DS_COMPLEMENTO VARCHAR(100) NOT NULL,
NM_BAIRRO VARCHAR(100) NOT NULL,
NR_FONERES NUMERIC(11) NOT NULL,
NR_FONECELU NUMERIC(11) NOT NULL,
NR_CPF_CNPJ INTEGER NOT NULL,
NR_GR_IE INTEGER NOT NULL,
DS_CIDADE VARCHAR(50) NOT NULL,
DS_UF CHAR(2) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CD_CLIENTE)
);

CREATE TABLE OPERADORA (
CD_OPERADORA INTEGER NOT NULL,
NM_OPERADORA VARCHAR(30) NOT NULL,
CONSTRAINT PK_OPERADORA PRIMARY KEY (CD_OPERADORA)
);

CREATE TABLE BANDEIRA (
CD_BANDEIRA INTEGER NOT NULL,
CD_OPERADORA INTEGER NOT NULL,
NM_BANDEIRA VARCHAR(30) NOT NULL,
CONSTRAINT FK_OPERADORA FOREIGN KEY (CD_OPERADORA) REFERENCES OPERADORA (CD_OPERADORA),
CONSTRAINT PK_BANDEIRA PRIMARY KEY (CD_BANDEIRA)
);

CREATE TABLE BANCO (
CD_BANCO INTEGER NOT NULL,
NM_BANCO VARCHAR (50) NOT NULL,
CONSTRAINT PK_BANCO PRIMARY KEY (CD_BANCO)
);

CREATE TABLE AGENCIA (
CD_AGENCIA INTEGER NOT NULL,
CD_BANCO INTEGER NOT NULL,
CD_CIDADE INTEGER NOT NULL,
NM_RUA VARCHAR(100) NOT NULL,
NR_RUA INTEGER NOT NULL,
NR_TELEFONE INTEGER NOT NULL,
DS_COMPLEMENTO VARCHAR(50) NOT NULL,
NM_BAIRRO VARCHAR(50) NOT NULL,
DS_CIDADE VARCHAR(50) NOT NULL,
DS_UF CHAR(2) NOT NULL,
CONSTRAINT FK_BANCO FOREIGN KEY (CD_BANCO) REFERENCES BANCO (CD_BANCO),
CONSTRAINT PK_AGENCIA PRIMARY KEY (CD_AGENCIA, CD_BANCO)
);

CREATE TABLE CONTA_CLIENTE (
CD_CONTA INTEGER NOT NULL,
CD_CLIENTE INTEGER NOT NULL,
CD_BANCO INTEGER NOT NULL,
CD_AGENCIA INTEGER NOT NULL,
VL_LIMITE NUMBER(8,2) NOT NULL,
VL_SALDO NUMBER(8,2) NOT NULL,
DS_TIPO_CONTA VARCHAR(30) NOT NULL,
CONSTRAINT FK_AGENCIA_ FOREIGN KEY (CD_AGENCIA, CD_BANCO) REFERENCES AGENCIA (CD_AGENCIA, CD_BANCO),
CONSTRAINT FK_CLIENTE_C FOREIGN KEY (CD_CLIENTE) REFERENCES CLIENTE (CD_CLIENTE),
CONSTRAINT PK_CONTA_CLIENTE PRIMARY KEY (CD_CONTA));

CREATE TABLE OPERACAO (
CD_OPERACAO INTEGER NOT NULL,
CD_CONTA_FAVOREVIDA INTEGER,
CD_CONTA INTEGER NOT NULL,
CD_TIPO_OPERACAO INTEGER NOT NULL,
CD_BANCO INTEGER NOT NULL,
CD_AGENCIA INTEGER NOT NULL,
DT_OPERACAO DATE NOT NULL,
HR_OPERACAO DATE NOT NULL,
VL_OPERACAO NUMERIC NOT NULL,
DS_OBSERVACAO VARCHAR(50),
CONSTRAINT FK_TIPO_OPERACAO FOREIGN KEY (CD_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO(CD_TIPO_OPERACAO),
CONSTRAINT FK_AGENCIA FOREIGN KEY (CD_AGENCIA, CD_BANCO) REFERENCES AGENCIA(CD_AGENCIA, CD_BANCO),
CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (CD_CONTA) REFERENCES CONTA_CLIENTE (CD_CONTA),
CONSTRAINT PK_OPERACAO PRIMARY KEY (CD_OPERACAO));

CREATE TABLE TIPO_OPERACAO(
CD_TIPO_OPERACAO INTEGER NOT NULL,
DS_TIPO_OPERACAO VARCHAR(50) NOT NULL,
CONSTRAINT PK_TIPO_OPERACAO PRIMARY KEY (CD_TIPO_OPERACAO)
);

CREATE TABLE CARTAO (
CD_CARTAO INTEGER,
CD_CONTA INTEGER,
CD_BANDEIRA INTEGER,
DS_TIPO VARCHAR(30),
CONSTRAINT FK_BANDEIRA FOREIGN KEY (CD_BANDEIRA) REFERENCES BANDEIRA (CD_BANDEIRA),
CONSTRAINT FK_CONTA_CLIENTE_CART FOREIGN KEY (CD_CONTA) REFERENCES CONTA_CLIENTE (CD_CONTA),
CONSTRAINT PK_CARTAO PRIMARY KEY (CD_CARTAO)
);