CREATE TABLE UF (
DS_UF CHAR(2),
CONSTRAINT PK_UF PRIMARY KEY (DS_UF)
);

CREATE TABLE CITY (
CD_CITY INTEGER,
DS_CITY VARCHAR(50) NOT NULL,
DS_UF CHAR(2) NOT NULL,
CONSTRAINT PK_CITY PRIMARY KEY (CD_CITY),
CONSTRAINT FK_UF FOREIGN KEY (DS_UF) REFERENCES UF (DS_UF)
);

CREATE TABLE CLIENT (
CD_CLIENT INTEGER,
CD_CITY INTEGER,
NM_CLIENT VARCHAR(50) NOT NULL,
DS_ADDRESS VARCHAR(100),
NR_ADDRESS INTEGER,
DS_COMPLEMENT VARCHAR(100),
NR_PHONE INTEGER,
CONSTRAINT FK_CITY FOREIGN KEY (CD_CITY) REFERENCES CITY (CD_CITY),
CONSTRAINT PK_CLIENT PRIMARY KEY (CD_CLIENT)
);

CREATE TABLE DELIVERY (
CD_DELIVERY INTEGER,
CD_CLIENT INTEGER,
DS_NOTE VARCHAR(300),
IN_SITUATION VARCHAR(10),
DT_DELIVERY DATE,
DT_CONCLUSION DATE,
HR_EXIT TIMESTAMP,
HR_COMING TIMESTAMP,
DS_OBSERVATION VARCHAR(100),
CONSTRAINT FK_CLIENT FOREIGN KEY (CD_CLIENT) REFERENCES CLIENT (CD_CLIENT),
CONSTRAINT PK_DELIVERY PRIMARY KEY (CD_DELIVERY)
);