/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.test.projectdelivery.vision;

import br.test.projectdelivery.control.ClassCity;
import br.test.projectdelivery.control.ClassClient;
import br.test.projectdelivery.control.ClassUF;
import br.test.projectdelivery.tools.FillJTable;

/**
 *
 * @author CrasyFox
 */
public class ClientQuery extends javax.swing.JDialog {

    public int keys[];
    public String keysString[];
    ClassClient client = new ClassClient();
    ClassCity city = new ClassCity();
    ClassUF uf = new ClassUF();
    FillJTable fillJTable = new FillJTable();
    
    public ClientQuery(java.awt.Frame parent, boolean modal, ClassClient client) {
        super(parent, modal);
        this.client = client;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCBOtherFind = new javax.swing.JComboBox<>();
        jCBTipFind = new javax.swing.JComboBox<>();
        jTFFindClient = new javax.swing.JTextField();
        jBFindClient = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTClientFind = new javax.swing.JTable();
        jCBTipFind1 = new javax.swing.JComboBox<>();
        jCBOtherFind1 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCBOtherFind.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jCBTipFind.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCBTipFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Code", "Name", "City", "UF" }));
        jCBTipFind.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCBTipFindPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jCBTipFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipFindActionPerformed(evt);
            }
        });

        jBFindClient.setText("Find");
        jBFindClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFindClientActionPerformed(evt);
            }
        });

        jTClientFind.setAutoCreateRowSorter(true);
        jTClientFind.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "City", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientFind.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTClientFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientFindMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTClientFind);

        jCBTipFind1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCBTipFind1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Code", "Name", "City", "UF" }));
        jCBTipFind1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCBTipFind1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jCBTipFind1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipFind1ActionPerformed(evt);
            }
        });

        jCBOtherFind1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBOtherFind, 0, 0, Short.MAX_VALUE)
                            .addComponent(jCBTipFind, 0, 0, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBOtherFind1, 0, 0, Short.MAX_VALUE)
                            .addComponent(jCBTipFind1, 0, 107, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTFFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBFindClient)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBTipFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBOtherFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBTipFind1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBOtherFind1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBTipFindPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBTipFindPopupMenuWillBecomeInvisible
        switch (jCBTipFind.getSelectedIndex()) {
            case 0 :
            case 1 :
            case 2 :
            jCBOtherFind.removeAllItems();
            break;
            case 3:
            keys = fillJTable.fillJComboReturn(city.queryGeneral(), jCBOtherFind, "CD_CITY", "DS_CITY");
            break;
            case 4:
            keysString = fillJTable.fillJComboReturnString(uf.queryGeneral(), jCBOtherFind, "DS_UF", "DS_UF");
            break;
        }
    }//GEN-LAST:event_jCBTipFindPopupMenuWillBecomeInvisible

    private void jCBTipFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipFindActionPerformed

    private void jBFindClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFindClientActionPerformed
        String[] columns = {"CD_CLIENT", "NM_CLIENT", "DS_CITY", "NR_PHONE"};
        switch (jCBTipFind.getSelectedIndex()) {
            case 0:
            fillJTable.fillJTableColumn(jTClientFind, client.queryGeneral(), columns );
            break;
            case 1:
            client.setCdClient(Integer.parseInt(jTFFindClient.getText()));
            fillJTable.fillJTableColumn(jTClientFind, client.queryCdClient(), columns);
            break;
            case 2:
            client.setNmClient(jTFFindClient.getText());
            fillJTable.fillJTableColumn(jTClientFind, client.queryNameClient(), columns);
            break;
            case 3:
            client.setCdCity(keys[jCBOtherFind.getSelectedIndex()]);
            fillJTable.fillJTableColumn(jTClientFind, client.queryCdCity(), columns);
            break;
            case 4:
            client.setUf(keysString[jCBOtherFind.getSelectedIndex()]);
            fillJTable.fillJTableColumn(jTClientFind, client.queryDsUF(), columns);
            break;
        }
    }//GEN-LAST:event_jBFindClientActionPerformed

    private void jCBTipFind1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBTipFind1PopupMenuWillBecomeInvisible

    }//GEN-LAST:event_jCBTipFind1PopupMenuWillBecomeInvisible

    private void jCBTipFind1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipFind1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipFind1ActionPerformed

    private void jTClientFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientFindMouseClicked
        client.setCdClient(Integer.parseInt(jTClientFind.getModel().getValueAt(jTClientFind.getSelectedRow(), 0).toString()));
        this.dispose();
    }//GEN-LAST:event_jTClientFindMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFindClient;
    private javax.swing.JComboBox<String> jCBOtherFind;
    private javax.swing.JComboBox<String> jCBOtherFind1;
    private javax.swing.JComboBox<String> jCBTipFind;
    private javax.swing.JComboBox<String> jCBTipFind1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTClientFind;
    private javax.swing.JTextField jTFFindClient;
    // End of variables declaration//GEN-END:variables
}
