/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.test.projectdelivery.vision;

import br.test.projectdelivery.control.ClassCity;
import br.test.projectdelivery.control.ClassClient;
import br.test.projectdelivery.control.ClassUF;
import br.test.projectdelivery.tools.FillJTable;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * 03/04/2016
 *
 * @author CrasyFox
 */
public class JFRegister extends javax.swing.JFrame {

    ClassCity city = new ClassCity();
    FillJTable fillJTable = new FillJTable();
    ClassUF uf = new ClassUF();
    ClassClient client = new ClassClient();
    int[] keys;
    String[] keysString;

    /**
     * 03/04/2016 Creates new form JFRegister
     */
    public JFRegister() {
        initComponents();
        fillJTable.alignTable(jTFindCity, new int[]{80, 200, 80});
        fillJTable.alignTable(jTClientFind, new int[]{50, 400, 100, 100});
        fillJTable.fillJcombo(uf.queryGeneral(), jCBUF, "DS_UF");
        fillJTable.fillJcombo(uf.queryGeneral(), jCBClientUF, "DS_UF");
    }

    public void getClientComponents() {
        client.setNmClient(jTFClientName.getText());
        client.setDsAddress(jTFClientAddress.getText());
        client.setNrAddress(Integer.parseInt(jTFClientNumber.getText()));
        client.setCdCity(keys[jCBClientCity.getSelectedIndex()]);
        client.setDsComplement(jTFClientComplement.getText());
        client.setNrPhone(Integer.parseInt(jTFClientPhone.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPFindCity = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFClientCode = new javax.swing.JTextField();
        jCBClientCity = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTFClientAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFClientName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFClientNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFClientComplement = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTFClientPhone = new javax.swing.JTextField();
        jCBClientUF = new javax.swing.JComboBox<>();
        jBIncludeClient = new javax.swing.JButton();
        jBAlterClient = new javax.swing.JButton();
        jBFill = new javax.swing.JButton();
        jBDeleteClient = new javax.swing.JButton();
        jBCancelClient = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTClientFind = new javax.swing.JTable();
        jTFFindClient = new javax.swing.JTextField();
        jBFindClient = new javax.swing.JButton();
        jCBOtherFind = new javax.swing.JComboBox<>();
        jCBTipFind = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTFCityCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFCityName = new javax.swing.JTextField();
        jBInclude = new javax.swing.JButton();
        jBAlter = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBCancelCity = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCBUF = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jBFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFindCity = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTPFindCity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTPFindCityStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Client Code:");

        jTFClientCode.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFClientCode.setText(" ");

        jCBClientCity.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCBClientCity.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCBClientCityPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Address:");

        jTFClientAddress.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Client Name:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Number:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("City");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("UF");

        jTFClientComplement.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Complement:");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Phone:");

        jCBClientUF.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCBClientUF.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCBClientUFPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jCBClientUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBClientUFActionPerformed(evt);
            }
        });

        jBIncludeClient.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jBIncludeClient.setText("Include");
        jBIncludeClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncludeClientActionPerformed(evt);
            }
        });

        jBAlterClient.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jBAlterClient.setText("Alter");
        jBAlterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterClientActionPerformed(evt);
            }
        });

        jBFill.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBFill.setText("Find");
        jBFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFillActionPerformed(evt);
            }
        });

        jBDeleteClient.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jBDeleteClient.setText("Delete");
        jBDeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteClientActionPerformed(evt);
            }
        });

        jBCancelClient.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jBCancelClient.setText("Cancel");
        jBCancelClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jTFClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBIncludeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jBAlterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jBDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jBCancelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFClientName)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jTFClientCode, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jBFill)))
                                    .addGap(0, 487, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTFClientAddress))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFClientNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(63, 63, 63)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jCBClientUF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(61, 61, 61)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jCBClientCity, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTFClientComplement))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFClientCode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFill, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFClientNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCBClientUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBClientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFClientComplement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIncludeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAlterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTPFindCity.addTab("Register Client", jPanel2);

        jTClientFind.setAutoCreateRowSorter(true);
        jTClientFind.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "City", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientFind.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTClientFind);

        jBFindClient.setText("Find");
        jBFindClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFindClientActionPerformed(evt);
            }
        });

        jCBOtherFind.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jCBTipFind.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCBTipFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Code", "Name", "City", "UF" }));
        jCBTipFind.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCBTipFindPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jCBTipFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBOtherFind, 0, 0, Short.MAX_VALUE)
                            .addComponent(jCBTipFind, 0, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBFindClient)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBTipFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBOtherFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTPFindCity.addTab("Find Client", jPanel4);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jTFCityCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCityCodeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("City Code :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("City Name :");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("City UF :");

        jBInclude.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBInclude.setText("Include");
        jBInclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncludeActionPerformed(evt);
            }
        });

        jBAlter.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBAlter.setText("Alter");
        jBAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterActionPerformed(evt);
            }
        });

        jBDelete.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBDelete.setText("Delete");

        jBCancelCity.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBCancelCity.setText("Cancel");
        jBCancelCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelCityActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFCityCode, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jBInclude, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jBAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                            .addComponent(jBCancelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTFCityName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jCBUF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCityCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInclude, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jTPFindCity.addTab("Register City", jPanel1);

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        jBFind.setText("Find");
        jBFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFindActionPerformed(evt);
            }
        });

        jTFindCity.setAutoCreateRowSorter(true);
        jTFindCity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTFindCity.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTFindCity);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(jBFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBFind)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPFindCity.addTab("Find City", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPFindCity)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPFindCity))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPFindCityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTPFindCityStateChanged
        update();
    }//GEN-LAST:event_jTPFindCityStateChanged

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained

    }//GEN-LAST:event_jPanel3FocusGained

    private void jBFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFindActionPerformed
        fillJTable.fillJTable(jTFindCity, city.queryGeneral());
    }//GEN-LAST:event_jBFindActionPerformed

    private void jBAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterActionPerformed
        city.setCdCity(Integer.parseInt(jTFCityCode.getText()));
        city.setDsCity(jTFCityName.getText());
        city.setDsUF(jCBUF.getSelectedItem().toString());
        city.alterCity();
        update();
    }//GEN-LAST:event_jBAlterActionPerformed

    private void jBIncludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncludeActionPerformed
        city.setDsCity(jTFCityName.getText());
        city.setDsUF(jCBUF.getSelectedItem().toString());
        city.includeCity();
        update();
    }//GEN-LAST:event_jBIncludeActionPerformed

    private void jTFCityCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCityCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCityCodeActionPerformed

    private void jCBClientCityPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBClientCityPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_jCBClientCityPopupMenuWillBecomeInvisible

    private void jCBClientUFPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBClientUFPopupMenuWillBecomeInvisible
        city.setDsUF(jCBClientUF.getSelectedItem().toString());
        keys = fillJTable.fillJComboReturn(city.queryUF(), jCBClientCity, "CD_CITY", "DS_CITY");
    }//GEN-LAST:event_jCBClientUFPopupMenuWillBecomeInvisible

    private void jBIncludeClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncludeClientActionPerformed
        client.setCdClient(Integer.parseInt(jTFClientCode.getText()));
        getClientComponents();
        client.includeClient();
        update();
    }//GEN-LAST:event_jBIncludeClientActionPerformed

    private void jBAlterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterClientActionPerformed
        client.setCdClient(Integer.parseInt(jTFClientCode.getText()));
        getClientComponents();
        client.alterClient();
        update();
    }//GEN-LAST:event_jBAlterClientActionPerformed

    private void jBCancelCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelCityActionPerformed
        update();
    }//GEN-LAST:event_jBCancelCityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        city.setCdCity(Integer.parseInt(jTFCityCode.getText()));
        jTFCityName.setText(fillJTable.getTextColumn(city.queryCode(), "DS_CITY"));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFillActionPerformed
        client.setCdClient(Integer.parseInt(jTFClientCode.getText()));
            jTFClientName.setText(fillJTable.getTextColumn(client.queryCdClient(), "NM_CLIENT"));
            jTFClientAddress.setText(fillJTable.getTextColumn(client.queryCdClient(), "DS_ADDRESS"));
            jTFClientComplement.setText(fillJTable.getTextColumn(client.queryCdClient(), "DS_COMPLEMENT"));
            jTFClientNumber.setText(fillJTable.getTextColumn(client.queryCdClient(), "NR_ADDRESS"));
            jTFClientPhone.setText(fillJTable.getTextColumn(client.queryCdClient(), "NR_PHONE"));
            jCBClientUF.setSelectedItem(fillJTable.getTextColumn(client.queryCdClient(), "DS_UF"));
            city.setDsUF(jCBClientUF.getSelectedItem().toString());
            fillJTable.fillJcombo(city.queryUF(), jCBClientCity, "DS_CITY");
            jCBClientCity.setSelectedItem(fillJTable.getTextColumn(client.queryCdClient(), "DS_CITY"));
        
    }//GEN-LAST:event_jBFillActionPerformed

    private void jBDeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteClientActionPerformed
        client.setCdClient(Integer.parseInt(jTFClientCode.getText()));
        client.deleteClient();
        update();
    }//GEN-LAST:event_jBDeleteClientActionPerformed

    private void jBCancelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelClientActionPerformed
        update();
    }//GEN-LAST:event_jBCancelClientActionPerformed

    private void jBFindClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFindClientActionPerformed
        String[] columns = {"CD_CLIENT", "NM_CLIENT", "DS_CITY", "NR_PHONE"};
        switch (jCBTipFind.getSelectedIndex()) {    
            case 0:                
                fillJTable.fillJTableColumn(jTClientFind, client.queryGeneral(), columns );
            break;    
            case 1:
                client.setCdClient(Integer.parseInt(jTFFindClient.getText()));
                fillJTable.fillJTableColumn(jTClientFind, client.queryCdClient(), columns);
                break;
            case 2:
                client.setNmClient(jTFFindClient.getText());
                fillJTable.fillJTableColumn(jTClientFind, client.queryNameClient(), columns);
                break;
            case 3:
                client.setCdCity(keys[jCBOtherFind.getSelectedIndex()]);
                fillJTable.fillJTableColumn(jTClientFind, client.queryCdCity(), columns);
                break;
            case 4:
                client.setUf(keysString[jCBOtherFind.getSelectedIndex()]);
                fillJTable.fillJTableColumn(jTClientFind, client.queryDsUF(), columns);
                break;
        }
    }//GEN-LAST:event_jBFindClientActionPerformed

    private void jCBTipFindPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBTipFindPopupMenuWillBecomeInvisible
        switch (jCBTipFind.getSelectedIndex()) {
            case 0:
                jCBOtherFind.removeAllItems();
            break;    
            case 1:
                jCBOtherFind.removeAllItems();
                break;
            case 2:
                jCBOtherFind.removeAllItems();
                break;
            case 3:
                keys = fillJTable.fillJComboReturn(city.queryGeneral(), jCBOtherFind, "CD_CITY", "DS_CITY");
                break;
            case 4:
                keysString = fillJTable.fillJComboReturnString(uf.queryGeneral(), jCBOtherFind, "DS_UF", "DS_UF");
                break;
        }
    }//GEN-LAST:event_jCBTipFindPopupMenuWillBecomeInvisible

    private void jCBTipFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipFindActionPerformed

    private void jCBClientUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBClientUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBClientUFActionPerformed

    private void update() {
        jTFClientCode.setText(client.autoIncrement("CD_CLIENT", "CLIENT"));
        jTFClientName.setText("");
        jTFClientAddress.setText("");
        jTFClientComplement.setText("");
        jTFClientNumber.setText("");
        jTFClientPhone.setText("");
        jTFCityCode.setText(city.autoIncrement("CD_CITY", "CITY"));
        jTFCityName.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlter;
    private javax.swing.JButton jBAlterClient;
    private javax.swing.JButton jBCancelCity;
    private javax.swing.JButton jBCancelClient;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBDeleteClient;
    private javax.swing.JButton jBFill;
    private javax.swing.JButton jBFind;
    private javax.swing.JButton jBFindClient;
    private javax.swing.JButton jBInclude;
    private javax.swing.JButton jBIncludeClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBClientCity;
    private javax.swing.JComboBox<String> jCBClientUF;
    private javax.swing.JComboBox<String> jCBOtherFind;
    private javax.swing.JComboBox<String> jCBTipFind;
    private javax.swing.JComboBox<String> jCBUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTClientFind;
    private javax.swing.JTextField jTFCityCode;
    private javax.swing.JTextField jTFCityName;
    private javax.swing.JTextField jTFClientAddress;
    private javax.swing.JTextField jTFClientCode;
    private javax.swing.JTextField jTFClientComplement;
    private javax.swing.JTextField jTFClientName;
    private javax.swing.JTextField jTFClientNumber;
    private javax.swing.JTextField jTFClientPhone;
    private javax.swing.JTextField jTFFindClient;
    private javax.swing.JTable jTFindCity;
    private javax.swing.JTabbedPane jTPFindCity;
    // End of variables declaration//GEN-END:variables
}
